ktor {
  application {
    modules = ["com.example.MyApplicationKt.myModule"]
  }

  deployment {
    port = 8081
    host = "0.0.0.0"
  }


   database {
    url = "jdbc:mariadb://localhost:3306/dbUser"
    driver = "org.mariadb.jdbc.Driver"
    username = "dani"
    password = "dani"
  }

}