ktor{
    application {
        modules = [ ktor.MyApplicationKt.myModule ]
    }
    deployment {
        port = 8081
        host = "0.0.0.0"
    }
    urlPath {
        baseUrl = "http://localhost:8081"
        images = "images"
        files = "files"
    }
    database {
        url = "jdbc:mariadb://localhost:3306/dbMoneyWise"
        driver = "org.mariadb.jdbc.Driver"
        username = "dani"
        password = "dani"
    }
    path {
        file = "upload/files"
        images = "upload/images"
    }
}
